---
# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: dev

replicaCount: 1

image:
  repository: geralex88/comment
  pullPolicy: Always
  tag: "2.0"

service:
  internalPort: 9292
  externalPort: 9292
  type: ClusterIP

databaseHost:

#ingress:
#  path: "/"
    
#service:
#  port: 8080
#  targetPort: 8080
#  #nodePort: 30005
#  type: ClusterIP
  