---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "comment.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
#    - host: www.example.com
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ template "comment.fullname" . }}
                port:
                  number: {{ .Values.service.externalPort }}
            path: {{ .Values.ingress.path }}
  # This section is only required if TLS is to be enabled for the Ingress
#  tls:
#    - hosts:
#      - www.example.com
#    - secretName: ui-ingress