apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  name: post
  labels:
    app: reddit
    component: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
      app: reddit
      component: post
  template:
    metadata:
      name: post
      labels:
        app: post
        app: reddit
        component: post
    spec:
      containers:
      - image: geralex88/post:2.0
        name: post
        env:
          - name: POST_DATABASE_HOST
            value: post-db
